---
  hostname: "localhost"
  port: 3000
  domain: "drivers.uz"
  log_file: "logs/vt.log"
  log_level: "debug" #info, warn, error
  postgresql: 
    host: "localhost"
    port: 5432
    user: "vt"
    pass: "vt"
    name: "vt"
    pool_size: 200
  redis: 
    host: "localhost"
    port: 6379
    db: 0
