---
  host: "localhost"
  port: 6001
  domain: "drivers.uz"
  log_file: "logs/vt.log"
  log_level: "debug" #info, warn, error
  postgresql: 
    host: "localhost"
    port: 5432
    user: "vt"
    pass: "vt"
    name: "vt"
    pool_size: 200
