---
  host: "localhost"
  port: 6001
  domain: "drivers.uz"
  log_file: "logs/vt.log"
  log_level: "debug" #info, warn, error
  gcm_api_key: "AIzaSyBBaV6nqZtFaQnKzRNK9i_g-jcBU77ji00"
  postgresql: 
    host: "localhost"
    port: 5432
    user: "vt"
    pass: "vt"
    name: "vt"
    pool_size: 200
  redis: 
    host: "localhost"
    port: 6379
    auth:
    db: 0
