---
  host: "127.0.0.1"
  port: 6001
  domain: "chat.drivers.uz"
  log_file: "logs/vt.log"
  log_level: "debug" #info, warn, error
  gcm_api_key: "gcm_api_key"
  robot_token: "robot_token"
  postgresql: 
    host: "db.drivers.uz"
    port: 5432
    user: "vt"
    pass: "vtvtvtvt"
    name: "vt"
    pool_size: 200
  redis: 
    host: "localhost"
    port: 6379
    auth:
    db: 0
