---
  host: "127.0.0.1"
  port: 6001
  domain: "chat.drivers.uz"
  log_file: "logs/vt.log"
  log_level: "debug" #info, warn, error
  gcm_api_key: "AIzaSyBBaV6nqZtFaQnKzRNK9i_g-jcBU77ji00"
  postgresql: 
    host: "vt.cgsrhj75wyom.us-west-2.rds.amazonaws.com"
    port: 5432
    user: "vt"
    pass: "vtvtvtvt"
    name: "vt"
    pool_size: 200
  redis: 
    host: "localhost"
    # host: "vt-qm.0rpdlx.0001.usw2.cache.amazonaws.com"
    port: 6379
    auth:
    db: 0
